name: 4DALERT_CHECK

on:
  workflow_run:
    workflows: ["dbt Cloud"]
    types:
       [completed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          USER_NAME: ${{secrets.USER_NAME}}
          P_W: ${{secrets.P_W}}
