name: 4DALERT_CHECK

on:
  pull_request:
    types: [opened, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          MY_TOKEN: ${{secrets.MY_TOKEN}}
          USER_NAME: ${{secrets.USER_NAME}}
          P_W: ${{secrets.P_W}}
